function [macPacket, deviceIndex] = addDestinationInfo(node, appPacket)
%addDestinationInfo Adds destination information to the App packet and
%creates MAC packet to be queued for transmission
%
%   Note: This is an internal undocumented function and its API and/or
%   functionality may change in subsequent releases.
%
%   [MACPACKET, DEVICEINDEX] = addDestinationInfo(NODE, APPPACKET) adds
%   destination information to the application packet and creates MAC
%   packet that can be queued for transmission.
%
%   MACPACKET is the MAC packet structure that can be queued for
%   transmission.
%
%   DEVICEINDEX is the source device ID on which the packet has to be sent
%   to reach the packet's destination.
%
%   NODE is an object of type wlanNode.
%
%   APPPACKET is the App packet structure generated by the application.

% Copyright 2023-2025 The MathWorks, Inc.

% Initialize
macPacket = node.MACQueuePacketTemplate;

macPacket.FrameBody.MSDU = appPacket;
macPacket.Header.TID = wlan.internal.Constants.AC2TID(appPacket.AccessCategory+1);

if node.IsMeshNode
    if node.IsAPNode % Hybrid mesh
        % Get node IDs of associated STAs and peer mesh nodes
        isDestinationAssociatedSTA = false;
        associatedSTAIDs = [node.RemoteSTAInfo(:).NodeID];
        destIdxLogical = appPacket.DestinationNodeID == associatedSTAIDs;
        if any(destIdxLogical) % Destination is an associated STA or peer mesh STA
            aid = node.RemoteSTAInfo(destIdxLogical).AID;
            isDestinationAssociatedSTA = (aid ~= 0); % Non-zero AID indicates destination is one of the associated STAs
        end
        if isDestinationAssociatedSTA
            [macPacket, deviceIndex] = addNonMLDDestinationInfo(node, macPacket, appPacket);
        else
            [macPacket, deviceIndex] = addMeshDestinationInfo(node, macPacket, appPacket);
        end
    else
        [macPacket, deviceIndex] = addMeshDestinationInfo(node, macPacket, appPacket);
    end
else % Non-mesh
    % Check if destination is an MLD
    isMLDDestination = wlan.internal.utils.isDestinationMLD(node, appPacket.DestinationNodeID);

    if node.IsMLDNode && isMLDDestination
        [macPacket, deviceIndex] = addMLDDestinationInfo(node, macPacket, appPacket);
    else
        [macPacket, deviceIndex] = addNonMLDDestinationInfo(node, macPacket, appPacket);
    end
end

end

function [macPacket, deviceIndex] = addMLDDestinationInfo(node, macPacket, appPacket)
%addMLDDestinationInfo Adds MLD destination info

    deviceIndex = 1;
    macPacket.Metadata.DestinationID = appPacket.DestinationNodeID;
    
    if node.IsAPNode
        destID = appPacket.DestinationNodeID;
        macPacket.Metadata.ReceiverID = destID;
        if destID == 65535 % Broadcast from AP
            macPacket.Header.Address1 = wlan.internal.utils.nodeID2MACAddress(destID);
            macPacket.Metadata.DestinationAddress = macPacket.Header.Address1;
        end
    else
        % STA sends packets to its associated AP. ReceiverID is the node ID of
        % associated AP and is independent of the link. Hence, consider link 1.
        macPacket.Metadata.ReceiverID = wlan.internal.utils.macAddress2NodeID(node.MAC(1).BSSID);
        macPacket.Metadata.DestinationAddress = wlan.internal.utils.nodeID2MACAddress(appPacket.DestinationNodeID);
    end
    
    % Not filling SourceAddress, and in some cases ReceiverAddress and
    % DestinationAddress because it is done at MAC after a specific link wins
    % contention
end

function [macPacket, deviceIndex] = addNonMLDDestinationInfo(node, macPacket, appPacket)
%addNonMLDDestinationInfo Adds non-MLD destination info

    if node.IsAPNode
        [deviceIndex, destAddress] = wlan.internal.utils.mapDestination2Device(node, appPacket.DestinationNodeID);
    
        % Fill immediate and final destination IDs and addresses
        macPacket.Metadata.ReceiverID = appPacket.DestinationNodeID;
        macPacket.Metadata.DestinationID = appPacket.DestinationNodeID;
        if deviceIndex ~= -1
            macPacket.Header.Address1 = destAddress;
            macPacket.Metadata.DestinationAddress = destAddress;
        end
    else
        [deviceIndex, destAddress] = wlan.internal.utils.mapDestination2Device(node, appPacket.DestinationNodeID);
        % Consider receiver is same as final destination. Change if
        % necessary in case of STA in BSS
        receiverAddress = destAddress;
        receiverID = appPacket.DestinationNodeID;
    
        if node.MAC(1).IsAssociatedSTA
            % Send data to the AP as the STA is associated to an AP
            receiverAddress = node.MAC.BSSID;
            receiverID = wlan.internal.utils.macAddress2NodeID(receiverAddress);
            if receiverID == appPacket.DestinationNodeID
                % If receiver is the final destination, assign final
                % destination address as receiver address
                destAddress = receiverAddress;
            end
        end
    
        % Fill immediate and final destination IDs and addresses
        macPacket.Metadata.DestinationID = appPacket.DestinationNodeID;
        macPacket.Metadata.DestinationAddress = destAddress;
        macPacket.Metadata.ReceiverID = receiverID;
        macPacket.Header.Address1 = receiverAddress;
    end
end

function [macPacket, sourceDeviceIdx] = addMeshDestinationInfo(node, macPacket, appPacket)
%addMeshDestinationInfo Add mesh destination info

    meshBridge = node.MeshBridge;
    macPacket.Metadata.DestinationID = appPacket.DestinationNodeID;
    
    % Get the next hop addresses for transmitting the data
    [sourceDeviceIdx, destinationAddress, meshDestinationAddress, nextHopAddress] = ...
        nextHop(meshBridge, appPacket.DestinationNodeID);
    
    if sourceDeviceIdx >= 0 % Further path exists
        macPacket.Metadata.DestinationAddress = destinationAddress;
        macPacket.Header.Address3 = meshDestinationAddress;
        if wlan.internal.utils.isDataFrame(macPacket)
            macPacket.FrameBody.MeshControl.Address5 = destinationAddress;
        end
        % If mesh destination is not in the next hop, then update the
        % next hop (receiver) address
        if ~strcmp(nextHopAddress, meshDestinationAddress)
            macPacket.Header.Address1 = nextHopAddress;
        else
            macPacket.Header.Address1 = meshDestinationAddress;
        end
    
        nextHopNode = wlan.internal.utils.macAddress2NodeID(macPacket.Header.Address1);
        macPacket.Metadata.ReceiverID = nextHopNode;
    else % No further path
        % sourceDeviceIdx == -1 (Proxy information present at node but path not found)
        % sourceDeviceIdx == -2 (Proxy information not present at node and path not found in forwarding table)
    
        % As the forward device index is unknown, increment forward
        % drop counter for first device
        deviceID = meshBridge.MAC(1).DeviceID;
        meshBridge.MeshStatistics(deviceID).DroppedMSDUsNoFurtherPath = meshBridge.MeshStatistics(deviceID).DroppedMSDUsNoFurtherPath + 1;
    end
end
