function remoteSTAInfo = defaultRemoteSTAInfo()
%defaultRemoteSTAInfo Returns default structure for storing remote STA info
%
%   Note: This is an internal undocumented function and its API and/or
%   functionality may change in subsequent releases
%
%   REMOTESTAINFO = defaultRemoteSTAInfo() returns default structure for
%   storing remote STA info. This structure is used to store information
%   about other nodes like associated STAs, peer mesh STAs, etc.

% Copyright 2025 The MathWorks, Inc.

remoteSTAInfo = struct(...
                    'NodeID', 0, ...
                    'MACAddress', '000000000000', ...
                    'DeviceID', 0, ...
                    'Mode', 'STA', ...
                    'AID', 0, ...
                    'IsMLD', false, ...
                    'EnhancedMLMode', 0, ...
                    'NumEMLPadBytes', 0, ...
                    'Bandwidth', 0, ...
                    'MaxSupportedStandard', wlan.internal.Constants.Std80211be);
end