function framebody = defaultMPDUFrameBody(frameType, triggerType)
%defaultMPDUFrameBody Returns a default structure for MPDU frame body
%
%   Note: This is an internal undocumented function and its API and/or
%   functionality may change in subsequent releases
%
%   FRAMEBODY = defaultMPDUFrameBody(FRAMETYPE) returns a default structure
%   for the framebody of an MPDU for the frame type specified by FRAMETYPE.
%
%   FRAMEBODY is a structure that varies for each frame type. Refer the
%   structures below under each frame type to see the fields under
%   framebody structure.
%
%   FRAMETYPE is a string specified the subtype of frame.
%
%   FRAMEBODY = defaultMPDUFrameBody(FRAMETYPE, TRIGGERTYPE) returns the
%   framebody structure for a trigger frame with the given value
%   TRIGGERTYPE assigned to TriggerType field.

% Copyright 2025 The MathWorks, Inc.

arguments
    frameType = 'QoS Data';
    triggerType = 'MU-RTS';
end

if strcmp(frameType, 'RTS') || strcmp(frameType, 'CTS') || strcmp(frameType, 'ACK') || strcmp(frameType, 'CF-End') || strcmp(frameType, 'QoS Null')
    framebody = [];

elseif strcmp(frameType, 'QoS Data')
    framebody = struct(...
                    'MeshControl', defaultMeshControl, ...
                    'MSDU', wlan.internal.utils.defaultMSDU);

elseif strcmp(frameType, 'Block Ack')
    framebody = struct(...
                    'TID', 0, ...
                    'SequenceNumber', 0, ...
                    'BlockAckBitmap', '0000000000000000');

elseif strcmp(frameType, 'Trigger')
    framebody = defaultTriggerFrameBody(triggerType);

elseif strcmp(frameType, 'Multi-STA-BA')
    framebody = struct(...
                    'UserInfo', struct('AID', 0, ...
                                    'TID', 0, ...
                                    'SequenceNumber', 0, ...
                                    'BlockAckBitmap', '0000000000000000'));

elseif strcmp(frameType, 'Beacon')
    framebody = struct(...
                    'Timestamp', 0, ...
                    'BeaconInterval', Inf, ...
                    'SSID', [], ...
                    'IsMeshBeacon', false, ...
                    'MeshID', [], ...
                    'ChannelBandwidth', 20, ...
                    'PrimaryChannel', 36, ...
                    'PrimaryChannelIndex', 1, ...
                    'BasicRates', [6 12 24], ...
                    'EDCAParamsCount', 0, ...
                    'AIFS', [3 7 2 2], ...
                    'CWMin', [15 15 7 3], ...
                    'CWMax', [1023 1023 15 7], ...
                    'TXOPLimit', 0, ...
                    'BSSColor', 0, ...
                    'NumMeshPeers', 0, ...
                    'IsAffiliatedWithMLD', false, ...
                    'MLDMACAddress', '000000000000', ...
                    'LinkID', 0, ...
                    'NumLinks', 0, ...
                    'MaxSupportedStandard', wlan.internal.Constants.Std80211be, ...
                    'RNRNeighborAPInfo', struct(...
                                            'LinkID', 0, ...
                                            'EDCAParamsCount', 0, ...
                                            'TBTTOffset', 0, ...
                                            'BSSIDList', []));
else
    framebody = [];
end
end

function framebody = defaultTriggerFrameBody(triggerType)
    if strcmp(triggerType, 'Basic') % Basic trigger
        framebody = struct(...
                        'TriggerType', triggerType, ...
                        'ChannelBandwidth', 20, ...
                        'CSRequired', 1, ...
                        'LSIGLength', 0, ...
                        'NumHELTFSymbols', 1, ...
                        'UserInfo', struct(...
                                        'AID12', 0, ...
                                        'MCS', 0, ...
                                        'RUSize', 0, ...
                                        'RUIndex', 0, ...
                                        'NumSpatialStreams', 1, ...
                                        'TIDAggregationLimit', 1, ...
                                        'PreferredAC', 0));
    
    elseif strcmp(triggerType, 'MU-RTS') % MU-RTS trigger
        framebody = struct(...
                        'TriggerType', triggerType, ...
                        'ChannelBandwidth', 20, ...
                        'CSRequired', 1, ...
                        'CommonInfoVariant', 'HE', ...
                        'HEorEHTP160', 1, ...
                        'SpecialUserInfoPresent', 0, ...
                        'NumPadBytesICF', 0, ...
                        'UserInfo', struct(...
                                        'AID12', 0, ...
                                        'UserInfoVariant', 'HE', ...
                                        'PS160', 0));
    
    elseif strcmp(triggerType, 'MU-BAR') % MU-BAR trigger
        framebody = struct(...
                        'TriggerType', triggerType, ...
                        'ChannelBandwidth', 20, ...
                        'CSRequired', 1, ...
                        'LSIGLength', 0, ...
                        'NumHELTFSymbols', 1, ...
                        'UserInfo', struct(...
                                        'AID12', 0, ...
                                        'MCS', 0, ...
                                        'RUSize', 0, ...
                                        'RUIndex', 0, ...
                                        'NumSpatialStreams', 1, ...
                                        'TID', 1, ...
                                        'StartingSequenceNum', 0));
    end
end

function meshControl = defaultMeshControl()
    meshControl = struct(...
                       'AddressExtensionMode', 0, ...
                       'Address5', '000000000000', ...
                       'Address6', '000000000000', ...
                       'MeshTTL', 31, ...
                       'MeshSequenceNumber', 0);
end