function s = defaultEventList()
% Returns a structure with event names as fields

%   Copyright 2024-2025 The MathWorks, Inc.

% Structure with event names as fields
s = struct('MPDUGenerated', 0, ...
    'MPDUDecoded', 0, ...
    'TransmissionStatus', 0, ...
    'StateChanged', 0, ...
    'AppDataReceived', 0);
end
