function isPacketQueued = sendPacketToMAC(node, packet)
%sendPacketToMAC Send a packet from higher layer to MAC queue
%
%   Note: This is an internal undocumented function and its API and/or
%   functionality may change in subsequent releases.
%
%   ISPACKETQUEUED = sendPacketToMAC(NODE, PACKET) inserts packet from
%   higher layer into MAC queue.
%
%   ISPACKETQUEUED is a flag indicating whether the packet is queued
%   successfully.
%
%   NODE is an object of type wlanNode.
%
%   PACKET is the packet structure generated by the higher layer i.e.,
%   application layer.

% Copyright 2025 The MathWorks, Inc.

% Do not allow packets exceeding the maximum MSDU size (2304 bytes)
% specified by the IEEE 802.11 Standard
if packet.PacketLength > 2304
    error(message('wlan:wlanNode:PacketSizeExceedsMaxMSDUSize', node.Name));
end
if isempty(packet.DestinationNodeID)
    packet.DestinationNodeID = node.BroadcastID;
end
[macQueuePacket, sourceDeviceIdx] = wlan.internal.utils.addDestinationInfo(node, packet);  % Add destination information to the packet
isGroupAddress = wlan.internal.utils.isGroupAddress(macQueuePacket.Header.Address1);       % Check if the destination is a groupcast address
isMLDDestination = wlan.internal.utils.isDestinationMLD(node, packet.DestinationNodeID);   % Check if the destination is an MLD

isPacketQueued = wlan.internal.pushDataToMAC(node, macQueuePacket, sourceDeviceIdx, isGroupAddress, isMLDDestination);
end